### ISSUE TITLE
Add a reload command to reload plugin language

### ISSUE THREAD

**Issue by YuanYuanOwO** [BlvckBytes/StorageQuery#4]
like:https://github.com/BlvckBytes/QuickShopSearch/issues/5

**Comment by BlvckBytes** [comment]
The [latest release](https://github.com/BlvckBytes/ItemPredicateParser/releases/tag/v0.0.7) now supports reloading the configuration-file. I've also added a playground-like feature to dispatch predicates on currently held items, namely `/ipp test <language> <predicate>`. Could you please be so kind as to also test whether sub-commands, to which the user has no permissions, are completely hidden? They shouldn't auto-complete or be suggested in usage-strings. If no sub-command can be accessed, the whole `/ipp` should be hidden. Thank you! :))

**Comment by YuanYuanOwO** [comment]
After testing it, I think it's working  
I also open a pull request,
